### ISSUE TITLE
Portuguese / Spanish not working

### ISSUE THREAD

**Issue by gleidsonh** [recognai/spacy-wordnet#4]
I have test to portuguese language but it's not working. Why?

```
Traceback (most recent call last):
  File "synonyms2.py", line 8, in <module>
    token = nlp('prices')[0]
  File "/home/gleidson/.local/lib/python3.8/site-packages/spacy/language.py", line 439, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))
  File "/home/gleidson/.local/lib/python3.8/site-packages/spacy_wordnet/wordnet_annotator.py", line 17, in __call__
    wordnet = Wordnet(token=token, lang=self.__lang)
  File "/home/gleidson/.local/lib/python3.8/site-packages/spacy_wordnet/wordnet_domains.py", line 31, in __init__
    self.__lang = fetch_wordnet_lang(lang)
  File "/home/gleidson/.local/lib/python3.8/site-packages/spacy_wordnet/__utils__.py", line 35, in fetch_wordnet_lang
    raise Exception('Language {} not supported'.format(lang))
Exception: Language pt not supported
```

And for Spanish, the synonyms were in English.

**Comment by dvsrepo** [comment]
Hi,

Portuguese support was added very recently to `master` and we have not yet tested it so it's not available when installing from `pip`.

We will test this and also the issue with Spanish that you mention.

**Comment by gleidsonh** [comment]
Nothing yet for installing from pip? I changed by my self and works great. Please, test and update. I can't use this way I'm doing because I need to build container from pip.

**Comment by dvsrepo** [comment]
Hi  @gleidsonh, we apologise for not taking care of this before. 

We have been testing this in master and it works for Spanish and Portuguese.

Regarding the synonyms appearing in English (I imagine you've sorted this out already), there's certainly a confusion with the example in the README, for getting lemmas in other languages you should pass the language to the nltk wn synset method (e.g., `s.lemma_names('por')`), will add examples in other langs now:

```python
economy_domains = ['finance', 'banking']
enriched_sentence = []
sentence = nlp(text)

# For each token in the sentence
for token in sentence:
    # We get those synsets within the desired domains
    synsets = token._.wordnet.wordnet_synsets_for_domain(economy_domains)
    if not synsets:
        enriched_sentence.append(token.text)
    else:
        lemmas_for_synset = [lemma for s in synsets for lemma in s.lemma_names('por')]
        # If we found a synset in the economy domains
        # we get the variants and add them to the enriched sentence
        enriched_sentence.append('({})'.format('|'.join(set(lemmas_for_synset))))

# Let's see our enriched sentence
print(' '.join(enriched_sentence))
# >> Eu (querer|desejar|esperar) retirar 5.000 euros
```

Could you please point us to the change you have done before installing on your Dockerfile?

We apologise for not catching up with the pip release, will do that before the end of next week. Meanwhile have you tried to pip install from master? Like:

`pip install -U git+https://github.com/recognai/spacy-wordnet.git`

Again sorry for the inconvenience, we've had no time to publish on pypi.

**Comment by gleidsonh** [comment]
I'm not so good on python, so I didn't know install this way you tell me. Anyway, the only change I did on Dockerfile was adding **pt='por'** to __utils__.py this way:

RUN sed -i "s/__WN_LANGUAGES_MAPPING = dict(es=__DEFAULT_LANG, en='eng')/__WN_LANGUAGES_MAPPING = dict(es=__DEFAULT_LANG, en='eng', pt='por')/" ${FUNCTION_DIR}/spacy_wordnet/__utils__.py

I don't know how install from master will works on built image, since all requirements is installed from requirements.txt.

RUN --mount=type=cache,target=/root/.cache/pip pip install -r ${FUNCTION_DIR}requirements.txt --target ${FUNCTION_DIR}

Anyway, if something wrong happens I'll tell you. Thanks for your help and you time. =]

**Comment by dvsrepo** [comment]
Thanks for your understanding.

In principle you could include this in the requirements.txt
https://stackoverflow.com/questions/16584552/how-to-state-in-requirements-txt-a-direct-github-source

Let us know how it goes but in any case we'll try to publish the new
version on pypi as soon as possible.
